stages:
  - build
  - deploy
  - deploy_prod

variables:
  APP_NAME: REPLACE_WITH_YOUR_NAME
  NAMESPACE: default
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  KUBEFOLDER: /root/.kube
  KUBECONFIG: $KUBEFOLDER/config
  BASE_CHART_TAG: v0.0.1

build_merge_request:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE -f Dockerfile --build-arg SSH_KEY="$SSH_KEY" .
  only:
    refs:
      - merge_requests

build:
  stage: build
  image: docker
  before_script:
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_BUILD_TOKEN
    - export VERSION=$(date -u +%Y%m%d%H%M%S).$CI_COMMIT_SHORT_SHA
  script:
    - docker build -t $CONTAINER_IMAGE:$VERSION --build-arg SSH_KEY="$SSH_KEY" .
    - docker push $CONTAINER_IMAGE:$VERSION
    - echo "export VERSION=$VERSION" >> variables
    - docker rmi -f $CONTAINER_IMAGE:$VERSION
  only:
    refs:
      - development
  artifacts:
    paths:
      - variables
    expire_in: 2 days

deploy_dev:
  stage: deploy
  image: dtzar/helm-kubectl:3.5.0
  variables:
    ENVIRONMENT: dev
  before_script:
    - mkdir ${KUBEFOLDER}
    - echo -n ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - source variables
  script:
    - helm repo add nexus http://10.120.212.202:8080/repository/helm-charts/ --username cicd --password Mee6yuXa
    - helm repo update
    - helm pull nexus/base-chart --untar --version ${BASE_CHART_TAG}
    - |
      sed -i -e "s/^\(version:\).*/\1 \"$VERSION\"/" -e "s/^\(appVersion:\).*/\1 \"$VERSION\"/" \
      -e "s/^\(name:\).*/\1 $APP_NAME/" base-chart/Chart.yaml
    - helm upgrade --install ${APP_NAME} ./base-chart --set image.repository=${CONTAINER_IMAGE},image.tag=${VERSION} --namespace ${NAMESPACE} -f deploy/${ENVIRONMENT}-values.yaml --wait --atomic
  only:
    refs:
      - development

build_tag:
  stage: build
  image: docker
  before_script:
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_BUILD_TOKEN
    - export VERSION=$CI_COMMIT_TAG
  script:
    - docker build -t $CONTAINER_IMAGE:$VERSION --build-arg SSH_KEY="$SSH_KEY" .
    - docker push $CONTAINER_IMAGE:$VERSION
    - docker rmi -f $CONTAINER_IMAGE:$VERSION
  only:
    refs:
      - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/

deploy_tag_dev:
  stage: deploy
  variables:
    ENVIRONMENT: dev
  image: dtzar/helm-kubectl:3.5.0
  before_script:
    - mkdir ${KUBEFOLDER}
    - echo -n ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - export VERSION=$CI_COMMIT_TAG
  script:
    - helm repo add nexus http://10.120.212.202:8080/repository/helm-charts/ --username cicd --password Mee6yuXa
    - helm repo update
    - helm pull nexus/base-chart --untar --version ${BASE_CHART_TAG}
    - |
      sed -i -e "s/^\(version:\).*/\1 $VERSION/" -e "s/^\(appVersion:\).*/\1 $VERSION/" \
      -e "s/^\(name:\).*/\1 $APP_NAME/" base-chart/Chart.yaml
    - helm upgrade --install ${APP_NAME} ./base-chart --set image.repository=${CONTAINER_IMAGE},image.tag=${VERSION} --namespace ${NAMESPACE} -f deploy/${ENVIRONMENT}-values.yaml --wait --atomic
  only:
    refs:
      - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/

deploy_tag_qa:
  variables:
    ENVIRONMENT: qa
  image: alpine/helm:3.3.4
  stage: deploy
  before_script:
    - export VERSION=$CI_COMMIT_TAG
  script:
    - helm repo add nexus http://10.120.212.202:8080/repository/helm-charts/ --username cicd --password Mee6yuXa
    - helm repo update
    - helm pull nexus/base-chart --untar --version ${BASE_CHART_TAG}
    - |
      sed -i -e "s/^\(version:\).*/\1 \"$VERSION\"/" -e "s/^\(appVersion:\).*/\1 \"$VERSION\"/" \
      -e "s/^\(name:\).*/\1 $APP_NAME/" base-chart/Chart.yaml
    - helm upgrade ${APP_NAME} ./base-chart --set image.repository=${CONTAINER_IMAGE},image.tag=${VERSION} -f deploy/${ENVIRONMENT}-values.yaml --namespace ${NAMESPACE} --install --wait --atomic
  tags:
    - qa-dcb-kube
  when: manual
  only:
    refs:
      - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/

deploy_tag_prod:
  variables:
    ENVIRONMENT: prod
  image: alpine/helm:3.3.4
  stage: deploy_prod
  before_script:
    - export VERSION=$CI_COMMIT_TAG
  script:
    - helm repo add nexus http://10.120.212.202:8080/repository/helm-charts/ --username cicd --password Mee6yuXa
    - helm repo update
    - helm pull nexus/base-chart --untar --version ${BASE_CHART_TAG}
    - |
      sed -i -e "s/^\(version:\).*/\1 \"$VERSION\"/" -e "s/^\(appVersion:\).*/\1 \"$VERSION\"/" \
      -e "s/^\(name:\).*/\1 $APP_NAME/" base-chart/Chart.yaml
    - helm upgrade ${APP_NAME} ./base-chart --set image.repository=${CONTAINER_IMAGE},image.tag=${VERSION} -f deploy/${ENVIRONMENT}-values.yaml --namespace ${NAMESPACE} --install --wait --atomic
  tags:
    - prod-dcb-kube
  when: manual
  only:
    refs:
      - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
